### ISSUE TITLE
Translate docs to English version

### ISSUE THREAD

**Issue by mechamobau** [betrybe/flipt-js#1]
The project creator team focused on creating docs in Portuguese, but to expand the number of people contributing with the project it's necessary to translate the documentations to a English version.

**Comment by jliocsar** [comment]
@mechamobau Hey! I'm interested on tackling this one 😄 
To get a clearer view though, the docs would be the monorepo's and its package's `README`s, right?
Should we create a `README.en.md` maybe?

**Comment by mechamobau** [comment]
Hey @jliocsar, thanks for the interest in contributing to the project!

> the docs would be the monorepo's and its package's READMEs, right?

Yes, right! :D

> Should we create a README.en.md maybe?

My idea is to make english the default language to the repo, so all `README`s can be translated to an english version and the current `README`s filenames renamed to `README.pt-br.md`. Does make sense?

If you have any other questions that I can respond to, please ask! I'm here if you need help ;)

**Comment by jliocsar** [comment]
@mechamobau Right! That sounds better indeed! Awesome, I'll open a PR when I have it done. Thanks! 😄
