### ISSUE TITLE
Create tests to createFliptSDK and its methods

### ISSUE THREAD

**Issue by mechamobau** [betrybe/flipt-js#5]
It's necessary to create tests to the function `createFliptSDK` and its methods to guarantee code quality and exemplify in more detail to new users.

Actually `createFliptSDK` has two methods (you can see [more about here](https://github.com/betrybe/flipt-js/tree/main/packages/flipt-sdk#api)):
- [ ] [evaluate](https://github.com/betrybe/flipt-js/blob/main/packages/flipt-sdk/src/createFliptSDK.ts#L30-L49)
- [ ] [batchEvaluate](https://github.com/betrybe/flipt-js/blob/main/packages/flipt-sdk/src/createFliptSDK.ts#L51-L65)

Both methods use `window.fetch` to make requests, mock these functions using the [Flipt API](https://flipt.io/docs/api/) as a reference.

**Comment by mateustalles** [comment]
Thanks @mechamobau !

**Comment by mateustalles** [comment]
@mechamobau  Hi! Sorry for the (huge) delay, work and kids were consuming my whole time and I was struggling with the Typescript with this exciting issue, but I managed to find a workaround!!

I hope those tests cover what you guys were expecting. Otherwise, let me know how I can improve.

Thanks!

**Comment by mechamobau** [comment]
Solved on #15
